=== auchMuffino/SolvdV2/HomeWork/16.12/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="cars">
    <xs:complexType>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="car">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="title" type="xs:string"/>
                        <xs:element name="top_speed" type="xs:integer"/>
                        <xs:element name="weight" type="xs:double"/>
                        <xs:element name="tank_capacity" type="xs:double"/>
                        <xs:element name="fuel_consumption" type="xs:double"/>
                        <xs:element name="fuel_level" type="xs:double"/>
                        <xs:element name="engine">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="engine_title" type="xs:string"/>
                                    <xs:element name="horse_powers" type="xs:integer"/>
                                    <xs:element name="capacity" type="xs:double"/>
                                    <xs:element name="is_broken" type="xs:boolean"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:schema>

=== auchMuffino/SolvdV2/HomeWork/16.12/test.xml
<?xml version="1.0"?>

<cars
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
    <car>
        <title>BMW</title>
        <top_speed>250</top_speed>
        <weight>2000</weight>
        <tank_capacity>20</tank_capacity>
        <fuel_consumption>4.0</fuel_consumption>
        <fuel_level>2.4</fuel_level>
        <engine>
            <engine_title>BMWW12</engine_title>
            <horse_powers>400</horse_powers>
            <capacity>0.6</capacity>
            <is_broken>false</is_broken>
        </engine>
    </car>
    <car>
        <title>BMW23</title>
        <top_speed>250</top_speed>
        <weight>2000</weight>
        <tank_capacity>20</tank_capacity>
        <fuel_consumption>4.0</fuel_consumption>
        <fuel_level>2.4</fuel_level>
        <engine>
            <engine_title>BMWW122</engine_title>
            <horse_powers>400</horse_powers>
            <capacity>0.6</capacity>
            <is_broken>false</is_broken>
        </engine>
    </car>
</cars>
